# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRxIftYqhK5KWVTpmDSWhSiWYQwZxkmq
"""

import streamlit as st
import os
import tempfile
import torch
from transformers import pipeline
from diffusers import StableDiffusionPipeline
from PIL import Image, ImageDraw, ImageFont
import moviepy.editor as mp
import pysrt
from langdetect import detect
import spacy

# Load models (cached to avoid reloading)
@st.cache_resource
def load_models():
    nlp = spacy.load("en_core_web_sm")  # For English; expand for more languages
    device = "cuda" if torch.cuda.is_available() else "cpu"
    pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16 if device == "cuda" else torch.float32)
    pipe.to(device)
    pipe.enable_attention_slicing()
    return nlp, pipe, device

nlp, pipe, device = load_models()

def detect_language(text):
    try:
        return detect(text)
    except:
        return "en"  # Fallback

def segment_text(text, lang):
    doc = nlp(text) if lang == 'en' else nlp(text)  # Placeholder for multilingual
    segments = [sent.text for sent in doc.sents]
    return segments

def generate_image(prompt, style="cartoon style"):
    full_prompt = f"{prompt}, {style}"
    image = pipe(full_prompt, num_inference_steps=20).images[0]
    return image

def create_subtitles(segments, duration_per_segment=3):
    subs = pysrt.SubRipFile()
    start_time = 0
    for i, seg in enumerate(segments):
        end_time = start_time + duration_per_segment
        sub = pysrt.SubRipItem(index=i+1, start=pysrt.SubRipTime(seconds=start_time), end=pysrt.SubRipTime(seconds=end_time), text=seg)
        subs.append(sub)
        start_time = end_time
    return subs

def create_video(images, subtitles, output_path, fps=1):
    clips = []
    for img in images:
        clip = mp.ImageClip(img).set_duration(3)  # 3 seconds per image
        clips.append(clip)
    video = mp.concatenate_videoclips(clips, method="compose")

    # Add subtitles overlay
    def add_text(get_frame, t):
        frame = get_frame(t)
        img = Image.fromarray(frame)
        draw = ImageDraw.Draw(img)
        try:
            font = ImageFont.truetype("arial.ttf", 40)  # Adjust path if needed (e.g., on Mac/Linux)
        except:
            font = ImageFont.load_default()
        current_sub = None
        for sub in subtitles:
            if sub.start.seconds <= t < sub.end.seconds:
                current_sub = sub.text
                break
        if current_sub:
            draw.text((50, img.height - 100), current_sub, fill="white", font=font)
        return img.tobytes()

    video = video.fl(add_text)
    video.write_videofile(output_path, fps=fps, codec="libx264", verbose=False, logger=None)

# Streamlit UI
st.title("Multilingual Text-to-Animated-Video Generator")
st.write("Paste your text (in any language), and generate a cartoon video with subtitles!")

text_input = st.text_area("Enter your text:", height=200, placeholder="Once upon a time, a little fox ran through the forest...")

if st.button("Generate Video"):
    if not text_input.strip():
        st.error("Please enter some text!")
    else:
        with st.spinner("Processing... This may take 5-15 minutes."):
            try:
                # Step 1: Detect language
                lang = detect_language(text_input)
                st.info(f"Detected language: {lang}")

                # Step 2: Segment text
                segments = segment_text(text_input, lang)
                st.write(f"Text segmented into {len(segments)} parts.")

                # Step 3: Generate images
                images = []
                progress_bar = st.progress(0)
                for i, seg in enumerate(segments):
                    prompt = f"Scene: {seg}"
                    img = generate_image(prompt)
                    images.append(img)
                    progress_bar.progress((i + 1) / len(segments))

                # Step 4: Create subtitles
                subs = create_subtitles(segments)

                # Step 5: Create video in temp file
                with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as temp_file:
                    output_path = temp_file.name
                create_video(images, subs, output_path)

                # Display video
                st.success("Video generated successfully!")
                st.video(output_path)

                # Download button
                with open(output_path, "rb") as f:
                    st.download_button("Download Video", f, file_name="generated_video.mp4", mime="video/mp4")

                # Cleanup (optional)
                os.unlink(output_path)

            except Exception as e:
                st.error(f"An error occurred: {str(e)}. Try shorter text or check your setup.")

st.write("---")
st.write("**Tips:** Keep text short (e.g., 2-3 sentences) for faster generation. For better results, experiment with prompts in the code.")

!pip install langdetect

!pip install pysrt

!pip install streamlit